#!/usr/bin/env python3
"""Generate corvid/strings/unicode_tables.h from Python's Unicode database.

The tokenizer pre-split rules (GPT-2's and every later one) classify code
points by the Unicode general categories Letter (L) and Number (N) and by
the White_Space property. Python's unicodedata module carries the general
category for every code point, so the tables come from it with no download.
White_Space is a property, not a category, and unicodedata does not expose
it; the list is short and stable, so it is spelled out here from PropList.txt.

The output is data only: sorted, disjoint, inclusive code point ranges. The
classifier that searches them is hand-written in the UTF-8 side quest.

Run from anywhere; the output path is fixed relative to the repository root.
"""

import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "corvid/strings/unicode_tables.h"
MAX_CP = 0x10FFFF

# White_Space property, Unicode PropList.txt. Unchanged since Unicode 6.
WHITE_SPACE = [
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
]

LICENSE = """\
// Corvid: A general-purpose modern C++ library extending std.
// https://github.com/stevensudit/Corvid
//
// Copyright 2022-2026 Steven Sudit
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"""


def ranges_for(major: str) -> list[tuple[int, int]]:
    """Collect inclusive ranges of code points whose category starts with major."""
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(MAX_CP + 2):
        hit = cp <= MAX_CP and unicodedata.category(chr(cp)).startswith(major)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def emit_table(name: str, doc: str, ranges: list[tuple[int, int]]) -> str:
    lines = [f"// {doc}", f"inline constexpr std::array<codepoint_range, {len(ranges)}> {name}{{{{"]
    for first, last in ranges:
        lines.append(f"    {{0x{first:04X}, 0x{last:04X}}},")
    lines.append("}};")
    return "\n".join(lines) + "\n"


def main() -> None:
    letters = ranges_for("L")
    numbers = ranges_for("N")
    version = unicodedata.unidata_version
    body = f"""{LICENSE}#pragma once
#include <array>

// Generated by scripts/gen_unicode_tables.py from Python's unicodedata
// (Unicode {version}). Do not edit by hand; rerun the script.
//
// Each table is a sorted list of disjoint, inclusive code point ranges for
// one Unicode class. The classifier that searches them is in unicode.h.

namespace corvid::strings::unicode {{

// Inclusive range of code points.
struct codepoint_range {{
  char32_t first;
  char32_t last;
}};

{emit_table("letter_ranges", "General category L (letter): Lu, Ll, Lt, Lm, Lo.", letters)}
{emit_table("number_ranges", "General category N (number): Nd, Nl, No.", numbers)}
{emit_table("white_space_ranges", "White_Space property (PropList.txt), which is what a regex backslash-s matches.", WHITE_SPACE)}
}} // namespace corvid::strings::unicode
"""
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: Unicode {version}, "
          f"{len(letters)} letter, {len(numbers)} number, "
          f"{len(WHITE_SPACE)} white_space ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
