#!/usr/bin/env python3
"""Generate corvid/strings/unicode_tables.h from Python's Unicode database.

The tables answer, for any code point, which of a small set of Unicode
properties it has: the general categories Letter (L) and Number (N), and the
White_Space property. Python's unicodedata module carries the general
category for every code point, so those come from it with no download.
White_Space is a property, not a category, and unicodedata does not expose
it; the list is short and stable, so it is spelled out here from PropList.txt.

The layout is a two-stage table. A code point's high bits select a page
through an index, and its low bits select a byte within that page; the byte
is a bitmap of the properties. Identical pages are shared, which is what
makes the structure small: most 256-code-point pages are entirely letters
or entirely unassigned, and the whole space collapses to a little over a
hundred distinct pages. The lookup is two loads and no branches.

Run from anywhere; the output path is fixed relative to the repository root.
The output is passed through clang-format when it is on the PATH, so the
committed file is stable under ./format_all.sh.
"""

import shutil
import subprocess
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "corvid/strings/unicode_tables.h"
MAX_CP = 0x10FFFF
PAGE_SHIFT = 8
PAGE_SIZE = 1 << PAGE_SHIFT

# Property bits. The classifier in unicode.h names these through the
# constants emitted below, never by value.
LETTER = 0x01
NUMBER = 0x02
WHITE_SPACE = 0x04

# White_Space property, Unicode PropList.txt. Unchanged since Unicode 6.
WHITE_SPACE_RANGES = [
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
]

LICENSE = """\
// Corvid: A general-purpose modern C++ library extending std.
// https://github.com/stevensudit/Corvid
//
// Copyright 2022-2026 Steven Sudit
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"""


def properties() -> bytes:
    """Return the property bitmap for every code point, indexed by code point."""
    out = bytearray(MAX_CP + 1)
    for cp in range(MAX_CP + 1):
        major = unicodedata.category(chr(cp))[0]
        if major == "L":
            out[cp] |= LETTER
        elif major == "N":
            out[cp] |= NUMBER
    for first, last in WHITE_SPACE_RANGES:
        for cp in range(first, last + 1):
            out[cp] |= WHITE_SPACE
    return bytes(out)


def paginate(values: bytes) -> tuple[list[bytes], list[int]]:
    """Split values into pages, sharing identical ones; return pages and index."""
    pages: dict[bytes, int] = {}
    index: list[int] = []
    for start in range(0, len(values), PAGE_SIZE):
        page = values[start : start + PAGE_SIZE]
        index.append(pages.setdefault(page, len(pages)))
    return list(pages), index


def emit_values(values: bytes | list[int]) -> str:
    # No trailing comma, so clang-format packs the elements to the column
    # limit instead of putting each on its own line.
    return ", ".join(str(v) for v in values)


def main() -> None:
    pages, index = paginate(properties())
    if len(pages) > 256:
        sys.exit(f"{len(pages)} pages no longer fit a one-byte index")
    version = unicodedata.unidata_version
    page_lines = ",\n".join(f"    {{{{{emit_values(page)}}}}}" for page in pages)
    body = f"""{LICENSE}#pragma once
#include <array>
#include <cstddef>
#include <cstdint>

// Generated by scripts/gen_unicode_tables.py from Python's unicodedata
// (Unicode {version}). Do not edit by hand; rerun the script.
//
// A two-stage property table. `property_index[cp >> page_shift]` selects a
// page, and the low `page_shift` bits of `cp` select a byte within it: a
// bitmap of the properties below. Identical pages are stored once.

namespace corvid::strings::unicode {{

inline constexpr char32_t max_code_point = 0x{MAX_CP:X};
inline constexpr size_t page_shift = {PAGE_SHIFT};

// General category L: Lu, Ll, Lt, Lm, Lo.
inline constexpr uint8_t letter_bit = 0x{LETTER:02X};

// General category N: Nd, Nl, No.
inline constexpr uint8_t number_bit = 0x{NUMBER:02X};

// The White_Space property (PropList.txt), which is what a regex
// backslash-s matches.
inline constexpr uint8_t white_space_bit = 0x{WHITE_SPACE:02X};

// The distinct pages, each covering {PAGE_SIZE} consecutive code points.
inline constexpr std::array<std::array<uint8_t, {PAGE_SIZE}>, {len(pages)}>
    property_pages{{{{
{page_lines}}}}};

// The page for each {PAGE_SIZE}-code-point block of the code space.
inline constexpr std::array<uint8_t, {len(index)}> property_index{{
    {emit_values(index)}}};

}} // namespace corvid::strings::unicode
"""
    OUT.write_text(body, encoding="utf-8")
    if clang_format := shutil.which("clang-format"):
        subprocess.run([clang_format, "-i", str(OUT)], check=True)
    print(f"wrote {OUT.relative_to(ROOT)}: Unicode {version}, "
          f"{len(index)} index entries, {len(pages)} distinct pages",
          file=sys.stderr)


if __name__ == "__main__":
    main()
